### ISSUE TITLE
Breakage on MATLAB 2014b

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler-1.0#3]
This forum user <a href="http://www.cellprofiler.org/forum/viewtopic.php?f=2&t=4110">reports</a> that runnning CP 1.0 from source on MATLAB 2014b produces the following error:

```
Error using get
There is no Behavior property on the UIControl class.

Error in CellProfiler>CellProfiler_LayoutFcn (line 5826)
h3 = uicontrol(...

Error in CellProfiler>gui_mainfcn (line 6356)
gui_hFigure = feval(gui_State.gui_LayoutFcn,
gui_SingletonOpt);

Error in CellProfiler (line 56)
gui_mainfcn(gui_State, varargin{:});

Error in run (line 63)
evalin('caller', [script ';']);
```

Apparently, there are some substantial UI changes with MATLAB 2014b: http://www.mathworks.com/help/matlab/gui-building-changes-in-r2014b.html.

**Comment by braymp** [comment]
@emmenlau, any input on this?

**Comment by emmenlau** [comment]
Hi,

On 05.01.2015 17:17, Mark Bray wrote:
> This forum user reports
> <http://www.cellprofiler.org/forum/viewtopic.php?f=2&t=4110> that runnning CP
> 1.0 from source on MATLAB 2014b produces the following error:
> 
> |Error using get
> There is no Behavior property on the UIControl class.
> 
> Error in CellProfiler>CellProfiler_LayoutFcn (line 5826)
> h3 = uicontrol(...
> 
> Error in CellProfiler>gui_mainfcn (line 6356)
> gui_hFigure = feval(gui_State.gui_LayoutFcn,
> gui_SingletonOpt);
> 
> Error in CellProfiler (line 56)
> gui_mainfcn(gui_State, varargin{:});
> 
> Error in run (line 63)
> evalin('caller', [script ';']);
> |
> 
> Apparently, there are some substantial UI changes with MATLAB 2014b:
> http://www.mathworks.com/help/matlab/gui-building-changes-in-r2014b.html.

I can confirm the problem. My personal experience with MATLAB 2014b
UI compatibility with former releases is actually relatively poor:
in my own code, several standard operations like using a figure handle
for printing fail with R2014b. Admittedly I did not check how much work
it would actually be to make CP1 R2014b-ready, but my gut feeling is
that its not worth it (given that CP1 works very well with all prior
releases, and there is no major benefit in Matlab R2014b over older
releases that I would be aware of, and given that CP2 is out and about
for quite a while now)?!

Let me know if you want to discuss it further!

Cheers,

     Mario



-- 
Mario Emmenlauer BioDataAnalysis             Mobil: +49-(0)151-68108489
Balanstrasse 43                    mailto: mario.emmenlauer * unibas.ch
D-81669 München                          http://www.biodataanalysis.de/

**Comment by braymp** [comment]
I agree that it's probably not worth the time to deal with now. I'll just leave the issue open in case an enterprising individual wants to run with it.
